[phases.setup]
nixPkgs = ['nodejs', 'openssl']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[variables]
PORT = '3000'

[start]
cmd = 'npm run start:prod'
